### ISSUE TITLE
Copying your work + putting stealer instead of legit (Not you)

### ISSUE THREAD

**Issue by Itroublve** [azaelgg/Jajaja-Account-Nuker#13]
Hello, so I came across a guy on YouTube, he had excluded some of the features of your nuker. Which OK, that's fine I thought. But when I downloaded it, it turned out to be a stealer... https://www.youtube.com/watch?v=6zP95akABlI, it will be really appreciated if you could take your time to Copyright Strike the video on basis of him "skidding" your source from here and advertising as his own. I think you shall do it because:
1) It's affecting your reputation, it's literally your nuker ==> people thinking you are the same guy
2) It's a stealer, stealing credentials
3) Well, it's simple. He isn't giving you any kind of credit or anything for the work you did.

I hope you'll be able to strike him and get rid of this piece of crap human. Thanks, again. This isn't meant towards you!

**Comment by azaelgg** [comment]
thank you for letting me know.
cheers

**Comment by CallMeIgnacio** [comment]
atm video got taken down, lol

**Comment by AstroOrbis** [comment]
Noice

**Comment by nickjayr** [comment]
good
